-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 12:04:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema financas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financas` DEFAULT CHARACTER SET utf8 ;
USE `financas` ;

-- -----------------------------------------------------
-- Table `financas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `desc_categoria` VARCHAR(255) NOT NULL,
  `obs_categoria` VARCHAR(255) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financas`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`conta` (
  `idconta` INT NOT NULL AUTO_INCREMENT,
  `conta` VARCHAR(255) NOT NULL,
  `desc_conta` VARCHAR(255) NULL,
  PRIMARY KEY (`idconta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financas`.`financas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`financas` (
  `idfinancas` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `forma_pagamento` ENUM('DINHEIRO', 'CREDITO', 'DEBITO', 'PIX') NOT NULL,
  `tipo` ENUM('RECEITA', 'DESPESA') NOT NULL,
  `situacao` ENUM('REALIZADO', 'NAO REALIZADO') NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `conta_idconta` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idfinancas`),
  INDEX `fk_financas_categoria_idx` (`categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_financas_conta1_idx` (`conta_idconta` ASC) VISIBLE,
  INDEX `fk_financas_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_financas_categoria`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `financas`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financas_conta1`
    FOREIGN KEY (`conta_idconta`)
    REFERENCES `financas`.`conta` (`idconta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financas_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `financas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
